#!/bin/bash
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf
ln -sf "$PWD/.p10k.zsh" "$HOME"/.p10k.zsh

curl -o "$HOME/.zshrc" https://raw.githubusercontent.com/Hamadn/dotfiles/main/.zshrc
curl -o "$HOME/.zprofile" https://raw.githubusercontent.com/Hamadn/dotfiles/main/.zprofile

packages=(
	fd
  	fzf
  	eza
  	bat
	tmux
  	thefuck
  	zoxide
	ripgrep
	powerlevel10k
	npm
	lazygit
	kubectl
	derailed/k9s/k9s
)


for package in "${packages[@]}"; do
	echo "Installing $package..."
	/home/linuxbrew/.linuxbrew/bin/brew install "$package"
done

echo "All packages from the setup script have been installed."
